# NumPy
- NumPy (short for Numerical Python) is a powerful open-source library in Python used for numerical computing. It’s one of the core building blocks for data science, machine learning, Generative AI and Agentic AI,.

### What NumPy does
- Multidimensional array
- Fast arrays: A special data structure called an ndarray (n-dimensional array) that stores numbers efficiently.
- Mathematical operations: Functions for performing calculations like addition, multiplication, trigonometry, statistics, and more—often much faster than plain Python.
- Linear algebra tools: Matrix operations, eigenvalues, dot products, etc.
Random number generation: Useful for simulations and machine learning.
### Why it’s important
- Speed: NumPy is implemented in optimized C code, so it runs much faster than regular Python loops.
- Convenience: You can perform operations on entire arrays without writing loops.
- Foundation for other libraries: Many popular tools like Pandas, Matplotlib, and Scikit-learn are built on top of NumPy.
- Handling numerical data inside agents
- Working with embeddings (vectors)
- Doing similarity calculations (cosine similarity, etc.)
- Supporting backend computations when needed

In [1]:
pip install  numpy

   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   -- ------------------------------------- 0.8/12.3 MB 5.6 MB/s eta 0:00:03
   ----- ---------------------------------- 1.8/12.3 MB 5.0 MB/s eta 0:00:03
   ---------- ----------------------------- 3.1/12.3 MB 5.6 MB/s eta 0:00:02
   ------------- -------------------------- 4.2/12.3 MB 5.2 MB/s eta 0:00:02
   ----------------- ---------------------- 5.2/12.3 MB 5.0 MB/s eta 0:00:02
   ------------------- -------------------- 6.0/12.3 MB 4.9 MB/s eta 0:00:02
   --------------------- ------------------ 6.6/12.3 MB 4.5 MB/s eta 0:00:02
   ------------------------- -------------- 7.9/12.3 MB 4.6 MB/s eta 0:00:01
   ---------------------------- ----------- 8.9/12.3 MB 4.7 MB/s eta 0:00:01
   -------------------------------- ------- 10.0/12.3 MB 4.6 MB/s eta 0:00:01
   ----------------------------------- ---- 11.0/12.3 MB 4.7 MB/s eta 0:00:01
   ---------------------------------------  12.1/12.3 MB 4.8 MB/s eta 0:00:01
   

In [3]:
import numpy as np 


In [7]:
mylist = [1, 2, 3, 4, 5]    
myarray = np.array(mylist)
print(myarray)


[1 2 3 4 5]


In [9]:
print(type(myarray))

<class 'numpy.ndarray'>


In [10]:
myarray.shape

(5,)

In [3]:
myarray.shape

(5,)

In [11]:
mylist1 = [1, 2, 3, 4, 5]
mylist2 = [6, 7, 8, 9, 10]
mylist3 = [11, 12, 13, 14, 15]

myarray=np.array([mylist1, mylist2, mylist3])
print(myarray)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [17]:
myarray

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [12]:
myarray.shape

(3, 5)

In [15]:
# reshape the array very fastly, dataset is in 12 rows and 1 column, we can reshape it to 4 rows and 3 columns
myarray.reshape(3, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [17]:
myarray.reshape(1, 15)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [18]:
myarray.shape

(3, 5)

## Indexing 

In [19]:
## accessing the elements of the array as rows
myarray[0]  # first row


array([1, 2, 3, 4, 5])

In [20]:
myarray

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [24]:
myarray[2][2] # first element of the array

np.int64(13)

In [29]:
myarray[0:2,0:2] # all rows and first two columns

array([[1, 2],
       [6, 7]])

In [30]:
myarray[1:,2:]

array([[ 8,  9, 10],
       [13, 14, 15]])

In [31]:
myarray

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [32]:
myarray[0:2, 2:4]

array([[3, 4],
       [8, 9]])

In [36]:
myarray=np.arange(1, 13,step=3)
myarray

array([ 1,  4,  7, 10])

In [37]:
#  linespace use for deep learning and machine learning, it is used to create a array of equally spaced numbers between a specified range.

myarray=np.linspace(0,10, num=50)  # 5 numbers between 0 and 10
myarray

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [38]:

myarray1 = np.array([1, 2, 3, 4, 5,6,7,8,9,10])
myarray1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
myarray1[5:]=100
myarray1

array([  1,   2,   3,   4,   5, 100, 100, 100, 100, 100])

In [40]:
myarray2=myarray1
myarray2

array([  1,   2,   3,   4,   5, 100, 100, 100, 100, 100])

In [41]:
myarray2[5:]=200
myarray2

array([  1,   2,   3,   4,   5, 200, 200, 200, 200, 200])

In [43]:
myarray1


array([  1,   2,   3,   4,   5, 200, 200, 200, 200, 200])

In [44]:
myarray2

array([  1,   2,   3,   4,   5, 200, 200, 200, 200, 200])

In [11]:
myarray

array([  1,   2,   3, 200, 200, 200, 200, 200, 200, 200])

In [46]:
myarray1=np.array([1, 2, 3, 4, 5,6,7,8,9,10])

In [47]:
myarray1[5:]=100
myarray1

array([  1,   2,   3,   4,   5, 100, 100, 100, 100, 100])

In [48]:
myarray2=myarray1.copy()
myarray2[5:]=200


In [49]:
myarray1

array([  1,   2,   3,   4,   5, 100, 100, 100, 100, 100])

In [50]:
myarray2

array([  1,   2,   3,   4,   5, 200, 200, 200, 200, 200])

In [129]:
# same codition
val= 100

myarray*2
myarray[myarray>val]


array([200, 200, 200, 200, 200, 200, 200])

In [58]:
arr1=np.arange(0,10).reshape(2,5)
arr2=np.arange(10,20).reshape(2,5)
print(arr1)
print(arr2)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[10 11 12 13 14]
 [15 16 17 18 19]]


In [59]:
arr1*arr2

array([[  0,  11,  24,  39,  56],
       [ 75,  96, 119, 144, 171]])

In [62]:
np.ones(10).reshape(2,5) # 2 rows and 3 columns of ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [64]:
np.ones(10,dtype=int).reshape(2,5) # 2 rows and 3 columns of ones with integer data type

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [66]:
# random numbers between 0 and 4
np.random.rand(5,5) # 2 rows and 3 columns of random numbers between 0 and 1

array([[0.08289864, 0.28069742, 0.68712388, 0.64545314, 0.10006354],
       [0.08214381, 0.41504879, 0.37686781, 0.35463488, 0.9922342 ],
       [0.10205743, 0.12250266, 0.37547203, 0.0526382 , 0.83102098],
       [0.62174054, 0.40110073, 0.08525181, 0.49547623, 0.20720004],
       [0.79551336, 0.17261352, 0.93843646, 0.78627682, 0.95536704]])

In [68]:
np.random.randint(0,200,20)

array([116, 107,  10,   9,  97, 125,  42,  77, 135, 181, 194,  79, 170,
         4,  39,  13, 111,  14, 135,  77], dtype=int32)

In [18]:
np.random.randint(0,100,10) # 2 rows and 3 columns of random integers between 0 and 4


array([41,  5, 87, 50, 40, 86, 81, 56, 97, 76], dtype=int32)