# Pandas
- Pandas is a popular library in Python used for data analysis and manipulation. It helps you work with structured data like tables (similar to Excel spreadsheets or SQL tables).

### What Pandas is used for
- Cleaning and preparing data
- Reading/writing data (CSV, Excel, databases, etc.)
- Filtering, sorting, and grouping data
- Performing calculations and statistics
- Handling missing values
- It’s powerful, easy to use, and integrates well with other tools like:  NumPy (for numerical operations), Matplotlib / Seaborn (for visualization), Machine learning libraries
### Core data structures
- Series → a single column (1D data)
- DataFrame → a table (rows and columns)
- different operations

In [1]:
pip install pandas


Note: you may need to restart the kernel to use updated packages.


In [2]:
import pandas as pd
import numpy as np


In [5]:
df =pd.DataFrame(np.arange(0,20).reshape(5,4),index=['Row1','Row2','Row3','Row4','Row5'],columns=['Col1','Col2','Col3','Col4'])
print(df)

      Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19


In [6]:
df.to_csv('myDataFrame.csv')

In [8]:
# accessing the element of the  dataframe
# 1)  .loc  --> names  "maha", "Age" and "a", "Co11", 'Rol1" 
# 2)  .iloc --> integer
print(df['Col1'])
print(df.loc['Row1'])

Row1     0
Row2     4
Row3     8
Row4    12
Row5    16
Name: Col1, dtype: int64
Col1    0
Col2    1
Col3    2
Col4    3
Name: Row1, dtype: int64


In [9]:
df.loc['Row1']

Col1    0
Col2    1
Col3    2
Col4    3
Name: Row1, dtype: int64

In [10]:
df.loc[:,:]

,Col1,Col2,Col3,Col4
Row1,0,1,2,3
Row2,4,5,6,7
Row3,8,9,10,11
Row4,12,13,14,15
Row5,16,17,18,19


In [13]:
df.loc['Row4':'Row5', 'Col3':'Col4']

,Col3,Col4
Row4,14,15
Row5,18,19


In [14]:
df.iloc[:,:]

,Col1,Col2,Col3,Col4
Row1,0,1,2,3
Row2,4,5,6,7
Row3,8,9,10,11
Row4,12,13,14,15
Row5,16,17,18,19


In [17]:
df.iloc[0:2,1:3]

,Col2,Col3
Row1,1,2
Row2,5,6


In [18]:
type(df.loc["Row1"])

pandas.Series

In [19]:
type(df.iloc[0:3,0:2])

pandas.DataFrame

In [20]:
df.iloc[:,:]

,Col1,Col2,Col3,Col4
Row1,0,1,2,3
Row2,4,5,6,7
Row3,8,9,10,11
Row4,12,13,14,15
Row5,16,17,18,19


In [21]:
df.iloc[0:,1:]

,Col2,Col3,Col4
Row1,1,2,3
Row2,5,6,7
Row3,9,10,11
Row4,13,14,15
Row5,17,18,19


In [22]:
df.values

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [26]:
df.iloc[0:3,0:2].values

array([[0, 1],
       [4, 5],
       [8, 9]])

In [27]:
df.iloc[0:3,0:2].values.shape

(3, 2)

In [28]:
df.isnull()

,Col1,Col2,Col3,Col4
Row1,False,False,False,False
Row2,False,False,False,False
Row3,False,False,False,False
Row4,False,False,False,False
Row5,False,False,False,False


In [29]:
df.isnull().sum()

Col1    0
Col2    0
Col3    0
Col4    0
dtype: int64

In [30]:
df

,Col1,Col2,Col3,Col4
Row1,0,1,2,3
Row2,4,5,6,7
Row3,8,9,10,11
Row4,12,13,14,15
Row5,16,17,18,19


In [35]:
df[['Col1','Col2']]

,Col1,Col2
Row1,0,1
Row2,4,5
Row3,8,9
Row4,12,13
Row5,16,17


In [39]:
df['Col1'].unique()

array([ 0,  4,  8, 12, 16])

In [44]:
df=pd.read_csv('mytest.csv', sep=';')
df.head()

,Unnamed: 0,Col1,Col2,Col3,Col4
0,Row1,0,1,2,3
1,Row2,4,5,6,7
2,Row3,8,9,10,11
3,Row4,12,13,14,15
4,Row5,16,17,18,19
